export default {
    '200': '',
    '400': 'Handle error',
    '401': 'Unauthorized',
    '402': 'Payment Required',
    '403': 'Forbidden',
    '404': 'Not Found',
    '405': 'Method Not Allowed',
    '406': 'Not Acceptable',
    '407': 'Proxy Authentication Required',
    '408': 'Request Time-out',
    '409': 'Conflict',
    '410': 'Gone',
    '411': 'Length Required',
    '412': 'Precondition Failed',
    '413': 'Request Entity Too Large',
    '414': 'Request-URI Too Large',
    '415': 'Unsupported Media Type',
    '416': 'Requested Range Not Satisfiable',
    '417': 'Expectation Failed',
    '418': "I'm a Teapot",
    '422': 'Unprocessed Entity',
    '423': 'Locked',
    '428': 'Precondition Required',
    '429': 'Too Many Requests',
    '430': 'Name existed',
    '431': 'Index is used',
    '432': 'Oid is not existed',
    '433': 'Reason is undefine',
    '434': 'Oid monitor value existed',

    '451': 'Unavailable For Legal Reasons',


    '500': 'Internal Server Error',
    '501': 'Not Implemented',
    '502': 'Bad Gateway',
    '503': 'Service Unavailable',
    '504': 'Gateway Time-out',
}